# Generated by Django 5.2.17 on 2026-08-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
