from datetime import timedelta
from decimal import Decimal
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.utils import timezone

from accounts.models import BusinessProfile
from consent.models import ConsentRecord
from imports.models import ImportFile, ImportedInvoice
from digital_twin.models import CashFlowTwin, CashFlowEntry, ForecastPoint
from analytics.engines.forecasting_engine import generate_forecast
from analytics.engines.risk_engine import update_risk_metrics
from market_analysis.models import ProductPriceReference


class Command(BaseCommand):
    help = "Create a ready-to-demo KhataTwin user and realistic sample cash-flow data."

    def add_arguments(self, parser):
        parser.add_argument("--username", default="demo")
        parser.add_argument("--password", default="Demo@12345")
        parser.add_argument("--reset", action="store_true")

    def handle(self, *args, **options):
        User = get_user_model()
        username = options["username"]
        password = options["password"]

        user, created = User.objects.get_or_create(
            username=username,
            defaults={"email": "demo@khatatwin.local", "first_name": "Demo"},
        )
        user.set_password(password)
        user.save()

        BusinessProfile.objects.update_or_create(
            user=user,
            defaults={
                "business_name": "Anand Textiles",
                "business_type": "Small Business",
                "industry": "Textiles",
                "monthly_revenue": Decimal("480000"),
                "monthly_fixed_expenses": Decimal("315000"),
            },
        )

        if options["reset"]:
            ImportFile.objects.filter(user=user).delete()
            CashFlowTwin.objects.filter(user=user).delete()
            ConsentRecord.objects.filter(user=user).delete()
            ProductPriceReference.objects.all().delete()

        now = timezone.now()
        for consent_type, purpose in [
            ("invoice", "Cash-flow forecasting"),
            ("payment", "Risk & delay analysis"),
            ("expense", "Liquidity forecasting"),
        ]:
            ConsentRecord.objects.update_or_create(
                user=user,
                consent_type=consent_type,
                defaults={
                    "purpose": purpose,
                    "granted": True,
                    "granted_at": now,
                    "revoked_at": None,
                    "expires_at": now + timedelta(days=90),
                },
            )

        import_file, _ = ImportFile.objects.get_or_create(
            user=user,
            file="imports/demo_invoices.txt",
            defaults={"file_type": "invoice", "status": "approved", "processed_at": now},
        )
        import_file.status = "approved"
        import_file.processed_at = now
        if not import_file.file:
            import_file.file.save("demo_invoices.txt", ContentFile(b"Demo data generated by seed_demo."), save=False)
        import_file.save()

        today = timezone.localdate()
        invoice_data = [
            ("INV-1042", "Anand Textiles", -5, 84000, 30000),
            ("INV-1050", "Rao Hardware Co.", 1, 46500, 0),
            ("INV-1055", "Anand Textiles", 6, 61000, 0),
            ("INV-1061", "Sundar Retail Group", -17, 132000, 0),
            ("INV-1066", "Priya Enterprises", 9, 27500, 0),
            ("INV-1070", "Anand Textiles", 18, 98000, 0),
        ]
        for number, customer, due_offset, amount, paid in invoice_data:
            due = today + timedelta(days=due_offset)
            invoice, _ = ImportedInvoice.objects.update_or_create(
                import_file=import_file,
                invoice_number=number,
                defaults={
                    "customer_name": customer,
                    "invoice_date": due - timedelta(days=30),
                    "due_date": due,
                    "amount": Decimal(str(amount)),
                    "paid_amount": Decimal(str(paid)),
                    "corrected": True,
                    "confidence_score": 0.99,
                },
            )

        twin, _ = CashFlowTwin.objects.get_or_create(user=user)
        CashFlowEntry.objects.filter(twin=twin).delete()
        expense_rows = [
            ("Payroll", 135000, 2, True),
            ("Supplier payments", 90000, 7, False),
            ("Rent", 42000, 10, True),
            ("Cloud & software", 18000, 14, True),
            ("Utilities", 12000, 20, False),
            ("Marketing", 15000, 25, False),
        ]
        for description, amount, offset, recurring in expense_rows:
            CashFlowEntry.objects.create(
                twin=twin,
                entry_type="expense",
                description=description,
                amount=Decimal(str(amount)),
                expected_date=today + timedelta(days=offset),
                recurring=recurring,
                source="demo",
            )

        # Add two historical actual entries so the ML forecast has a small history to learn from.
        for description, amount, days_ago, entry_type in [
            ("Historical sales collection", 72000, 3, "income"),
            ("Historical supplier payment", 38000, 2, "expense"),
            ("Historical sales collection", 61000, 9, "income"),
            ("Historical supplier payment", 31000, 8, "expense"),
            ("Historical sales collection", 68000, 15, "income"),
            ("Historical supplier payment", 35000, 14, "expense"),
        ]:
            CashFlowEntry.objects.create(
                twin=twin,
                entry_type=entry_type,
                description=description,
                amount=Decimal(str(amount)),
                expected_date=today - timedelta(days=days_ago),
                actual_date=today - timedelta(days=days_ago),
                source="demo-history",
            )

        twin = __import__("digital_twin.builder", fromlist=["build_cashflow_twin"]).build_cashflow_twin(user)
        generate_forecast(twin, days=90)
        update_risk_metrics(twin)

        ProductPriceReference.objects.bulk_create([
            ProductPriceReference(product_name="Cotton bedsheet set (queen)", category="Home textiles", supplier="Demo Supplier A", price=Decimal("1499"), source="Demo reference"),
            ProductPriceReference(product_name="Cotton bedsheet set (queen)", category="Home textiles", supplier="Demo Supplier B", price=Decimal("1599"), source="Demo reference"),
            ProductPriceReference(product_name="Cotton bedsheet set (queen)", category="Home textiles", supplier="Demo Supplier C", price=Decimal("1399"), source="Demo reference"),
        ], ignore_conflicts=True)

        self.stdout.write(self.style.SUCCESS("Demo environment is ready."))
        self.stdout.write(f"Username: {username}")
        self.stdout.write(f"Password: {password}")
        self.stdout.write("Business: Anand Textiles")
        self.stdout.write("Data: invoices, expenses, history, forecast, risk flags and market references")
