# Generated by Django 5.2.17 on 2026-08-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_collection_days', models.FloatField(default=0)),
                ('concentration_risk', models.FloatField(default=0)),
                ('delayed_payment_risk', models.FloatField(default=0)),
                ('liquidity_risk', models.FloatField(default=0)),
                ('survivable_loss_percent', models.FloatField(default=0)),
                ('emergency_savings_percent', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_twin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='digital_twin.cashflowtwin')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('liquidity_gap', models.BooleanField(default=False)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='digital_twin.cashflowtwin')),
            ],
        ),
    ]
